# This workflow releases new tagged versions on Github Releases

name: Release

on:
  push:
    tags:
      - [0-9]+.*


jobs:
  # Create a github release whenever we push a new tag
  create-release:
    if: github.repository_owner == 'brouberol' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1
        with:
          title: $version
          changelog: CHANGELOG.md
        env:
          # (required) GitHub token for creating GitHub Releases.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
